- name: "Configuring Master Node"
  hosts: master
  roles:
    - role: "K8SMaster"
  tasks:
    - name: "Getting join command"
      shell: "kubeadm token create  --print-join-command"
      register: join_command

    - set_fact:
        join_shared: "{{ join_command.stdout }}"

    - add_host:
        name: "value"
        join_shared: "{{ join_shared }}"

- name: "Configuring Worker Nodes"
  hosts: worker
  vars:
    join: "{{ hostvars['value']['join_shared'] }}"
  roles:
    - role: "K8SSlave"
  tasks:
    - name: "Passing joining command"
      shell: "{{ join }}"