- hosts: all
  vars:
    dvd_dir: "/dvd1"
    webPage_dir: "/root/WebHost/"
  tasks:
  - name: Creating a directory for DVD
    file:
      state: directory
      path: "{{dvd_dir}}"
  
  - name: Mounting the DVD to a directory
    mount:
      src: "/dev/sr1"
      path: "{{dvd_dir}}"
      state: mounted
      fstype: "iso9660"

  - name: Configuring the AppStream 
    yum_repository:
      name: mydvd1
      description: "YUM DVD for packages"
      baseurl: "{{dvd_dir}}/AppStream"
      gpgcheck: no

  - name: Configuring the BaseOS
    yum_repository:
      name: mydvd2
      description: "YUM DVD for packages"
      baseurl: "{{dvd_dir}}/BaseOS"
      gpgcheck: no

  - name: Configuring the docker 
    yum_repository:
      name: docker-url
      description: "Docker-ce url"
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
  
  - name: Installing the Docker-CE
    package:
      name: docker-ce-18.09.1-3.el7.x86_64
      state: present

  - name: Starting and enabling the Docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: Installing the docker SDK 
    command: "pip3 install docker-py"

  - name: Pull HTTPD image
    docker_image:
      name: httpd
      source: pull

  - name: Making a directory in managed node for WebPages
    file: 
      path: "{{webPage_dir}}"
      state: directory
  
  - name: Copy the file to the managed node
    copy: 
      src: "index.html" 
      dest: "{{webPage_dir}}"

  - name: WebServer container
    docker_container:
      name: WebServerContainer
      image: httpd
      volumes:
              -  "{{webPage_dir}}:/usr/local/apache2/htdocs/"
      ports:
              -  "81:80"
      state: started
      detach: yes

  - name: Allowing port 81 over firewall for TCP protocol
    firewalld:
      port: 81/tcp
      state: enabled
      permanent: yes
      immediate: yes

  - name: Add masquerading to the public zone.
    ansible.posix.firewalld: 
      masquerade: yes
      zone: public
      state: enabled
      permanent: yes
      immediate: yes
